### PR TITLE
feat: added faq button

### PR DESCRIPTION
**Pull request by its-me-Harsh-Anand**
- Added a Faq button
- Data to be filled in popup of FAQ
- PR of issue [https://github.com/lyqht/Octokit-lite/issues/35](https://github.com/lyqht/Octokit-lite/issues/35)

### CODE REVIEW

**Comment by lyqht** [comment]
Hello! Is this still in progress?

**Comment by its-me-Harsh-Anand** [comment]
> Hello! Is this still in progress?

Yes, actually I'm having exam....that's why taking some time...tomorrow for sure, it will be completed.

**Comment by lyqht** [comment]
Ah I see, no worries, all the best for your exam mate 😁

**Comment by its-me-Harsh-Anand** [comment]
@lyqht Please review the changes
- there is a FAQ button at the top-right corner, on clicking button will result this FAQ
image

**Comment by lyqht** [comment]
Hi @its-me-Harsh-Anand , the FAQ should be at `unfork/index.tsx` as mentioned in the issue.

The popup should be more opaque as well, a bit disorienting to see both the FAQ text and content behind the popup.

Thanks!

**Comment by its-me-Harsh-Anand** [comment]
> Hi @its-me-Harsh-Anand , the FAQ should be at `unfork/index.tsx` as mentioned in the issue.
> 
> The popup should be more opaque as well, a bit disorienting to see both the FAQ text and content behind the popup.
> 
> Add a header 'FAQ' too
> 
> Thanks!

Means I should use as well as define it in `index.tsx` since I'm only using it inside `index.tsx` but defined in `src/components/FaqButton.tsx`

**Comment by lyqht** [comment]
Sorry, I don't quite understand what you meant. From your current screenshot, the FAQ appears at the homepage, but I would like it to only be accessible from the Unfork page. Hence `unfork/index.tsx` instead of just `index.tsx`.

You could modify the FAQ component to take in props for specific text if you would like it to be reusable for other apps like topic space and Unlabel.

**Comment by its-me-Harsh-Anand** [comment]
> Sorry, I don't quite understand what you meant. From your current screenshot, the FAQ appears at the homepage, but I would like it to only be accessible from the Unfork page. Hence `unfork/index.tsx` instead of just `index.tsx`.
> 
> You could modify the FAQ component to take in props for specific text if you would like it to be reusable for other apps like topic space and Unlabel.

Sure, I'll modify the changes as required today

**Comment by its-me-Harsh-Anand** [comment]
- Added FAQ button to `unfork/index` which takes FAQ as input in the form of `HTML` to make the button reusable
- Added more opacity
- Added FAQ heading

**Comment by lyqht** [comment]
Hello @its-me-Harsh-Anand made some adjustments which you can refer to the commit messages above — basically making sure it looks ok on both desktop and mobile, update the header to not be a button, and add a close button on the faq content like a usual popup. Below shows the update.

Desktop view

Screenshot 2022-10-15 at 11 56 40 PM

Mobile view

Screenshot 2022-10-15 at 11 56 57 PM

---

Please add the hyperlinks, and I think the PR will be good for merge!

**Comment by its-me-Harsh-Anand** [comment]
Thanks @lyqht for helping me out to look FAQ good but which hyper link are you talking about? 🤔 
One that is written in Context portion of the issue #35 ?

**Comment by lyqht** [comment]
Yep the link to the GitHub docs on restoring deleted projects

**Comment by lyqht** [comment]
Thanks!

**Comment by its-me-Harsh-Anand** [comment]
> Thanks!
Thanks to you too sir for helping me out so much

**Pull request merged**
