### PR TITLE
feat: added sort by number of issues function in topicspace

### PR DESCRIPTION
**Pull request by then00bprogrammer**
this solves #11

### CODE REVIEW

**Comment by then00bprogrammer** [comment]
@lyqht please check if it's okay or some change needs to be made.
Thank You.

**Comment by lyqht** [comment]
Hi @then00bprogrammer , thanks for your work! As there's some update to the Repository picker component props in how repo metadata can be sorted  (due to #18), and that has been merged to `main`, please make the necessary changes.

Furthermore, please do not commit your console log/ comments, and also run `pnpm format && pnpm lint` for your commits

**Comment by then00bprogrammer** [comment]
alright, I'll take care of that and get back to you

**Comment by then00bprogrammer** [comment]
hey @lyqht could you be please regarding what changes you want me to make?

**Comment by lyqht** [comment]
Please help your sortGroup logic to the method with the same name in the common RepositoryPicker component

**Comment by lyqht** [comment]
Any updates on this?

**Comment by lyqht** [comment]
Closing due to inactivity

**Pull request closed without merging**
