### PR TITLE
Added UI for GitHub docs on restoring deleted projects #27

### PR DESCRIPTION
**Pull request by AlokMishra051298**
Added UI for GitHub docs on restoring deleted projects.

### CODE REVIEW

**Comment by AlokMishra051298** [comment]
image

Added UI for GitHub docs on restoring deleted projects issue #27

**Comment by AlokMishra051298** [comment]
@lyqht  Please have a look whenever you get some time :)

**Comment by lyqht** [comment]
Hi thanks for working on this!

Feedback on this PR related to the fact you might be new to contributing:
- Oh gosh. Next time, please create a new branch based off the latest main branch and start the PR from it. No project maintainer want to see irrelevant commits to the issue.
- Please also take a look at GitHub docs on words that help to close the issue in the PR description e.g. "Closes #X". This is your second PR and noticed u still haven't done this.

Feedback on the actual work:
- if the UI is just this text, then it's kinda bad. 
- first if doesn't look like a link and second, if users already have a lot of deleted records (I have 30+ deleted records), this link wont't be seen.
- please propose a better UI before reimplementing or otherwise implement the suggested solution in the issue.

**Comment by AlokMishra051298** [comment]
Now @lyqht ?
image

**Comment by lyqht** [comment]
A question icon would be better. This implies unfork has this restore functionality which it does not. Some padding between the word and icon will be good. How does it look on mobile?

**Comment by AlokMishra051298** [comment]
Okay lemme make it Question mark. My thought behind keeping Restore icon is that it conveys the idea better.

**Comment by AlokMishra051298** [comment]
Now ?
image

**Comment by lyqht** [comment]
If it's clearer, I meant a UI like [this](https://daisyui.com/components/alert/) but with a question icon that's appropriate.

**Comment by lyqht** [comment]
Text can be clearer like "How to restore deleted projects"

**Comment by AlokMishra051298** [comment]
@lyqht Isn't this message will look messy for mobile?

**Comment by lyqht** [comment]
Good point, that's where the responsive design aspect comes into play. You could choose to display a different UI for mobile or make the text smaller on mobile - enough to be read clearly. 

U can do a mockup first before implementing.

**Comment by AlokMishra051298** [comment]
Smaller Screen: 
image

Mid Size Screen:
image

Larger Screens:
image

**Comment by lyqht** [comment]
The text size is ok! But the whole thing should be clickable. so use a circle surrounding a question symbol like the alert UI. And then don't use glass style on anything within this UI (for now its only on the back button). You can use like info or primary styles of daisy ui.

**Comment by AlokMishra051298** [comment]
Now @lyqht ?
image

image

**Comment by lyqht** [comment]
hi, yes the symbol looks as intended now. it should be placed on the left of the text. but this UI does not look like a button

**Comment by AlokMishra051298** [comment]
I think button will look messy.

**Comment by lyqht** [comment]
Hmm ok I guess you can commit the change then I can merge the PR. I'm still not impressed with this UI but it works for now

**Pull request merged**
