### PR TITLE
Feature/unlabel

### PR DESCRIPTION
**Pull request by Dolir**
Added new feature Unlabel 
Closes issue #33

### CODE REVIEW

**Comment by lyqht** [comment]
Awesome work! A few feedback:
1. I've tested the happy e2e flow, **works good as intended** 👏 able to remove label and see the updated record in the history page.
2. **Unhappy e2e flow** problem: When i try to remove a label from a repo that does not have the label, I get the following error.
    image
    - In fact, I **only selected 1 repo**, so I was a bit shocked to see "42 repos" in the error text 😆
    - I saw that in your method `updateReposWithLabels`, you do have a check for whether the label exists, so not too sure what caused the above. Please help to look into it. 
3. Performance issue: if your refer to the screenshot below, now it's taking ~6s for the page to load (I have 89 repos). 
  image

  - This happens on both navigating from homepage and navigating from its history page. 
  - The other two apps takes ~2s which is still ok for now, but 6s is a bit too long. 
  - I understand it's because of how we are performing the api requests right now (we fetch every page of get repos, and then we fetch every label for each repo)
  - To improve this without making too many changes, perhaps we can move the fetch for issues to the frontend instead (e.g. onMount), then we update the state to show the labels. When no labels are fetched, the label can show "Loading..." at each row. Would love to hear other suggestions by you @Dolir as well!

**Comment by lyqht** [comment]
added some commits for minor text/styling/png to svg things.

**Comment by lyqht** [comment]
Thanks for making the quick update on fetching labels and fixing the error catch! 😄

Actually if we select many repos, and it just so happens one of them does not have the label, can we skip making the update label GitHub API call for that repo instead and not throw an error for the whole API call? Additionally, we will not create the supabase DB updated record for that repo since no label is actually deleted.

**Comment by Dolir** [comment]
Now it skips repos if cant find any labels that are needed to be removed

**Pull request merged**
