### PR TITLE
Fix:[Unfork] Reset repository picker options after submission [fixes #25]

### LINKED ISSUE #25: [Unfork] Reset repository picker options after submission
## Description

Currently at Unfork, after deleting repositories, those repositories stay as options. 

**The `RepositoryPicker` component should reset options after user has submitted the repositories for deletion.**

> For TopicSpace, i think it is ok to leave the repositories selected there after users updated the topics as they might wanna add more topics to the same selected topics.

## Relevant code

- `unfork/index.tsx` -> Probably just need to reset the `selectedItems` state here. 
 
But there may be unintended UX behaviors caused by downshift component after resetting the state, so please play around with the dropdown after making the changes to ensure that the component still work as intended.

### PR DESCRIPTION
**Pull request by najeebkp**
#### small setSelectedItem([]) change added after the delete response.

### CODE REVIEW

**Comment by lyqht** [comment]
hi @najeebkp, currently there's a behavior that after you deleted an item and reset the selectedItems state, the dropdown doesn't jump back to the top — might be something to do with `highlightedIndex`. could you help to look into that?

**Comment by najeebkp** [comment]
i didn't understand. can you show some screenshots and explain?

**Comment by lyqht** [comment]
Initial state

image

After deleting repositories — it doesn't automatically back up to the top of the dropdown, so you can't see the group label. 

image

**Comment by najeebkp** [comment]
Hey i checked it for couple of hours. Actually setHighlighted index works -> so that it takes to the 0th index. but it doesnot recognises the top filter as an element. that is the issue. i couldn't find a solution to fix that.

**Comment by lyqht** [comment]
Hello thanks for looking into it! Could you see if it's possible to attach a ref to the drop-down and scroll to the top of that drop-down after you have set the selected items as an empty array?

**Comment by najeebkp** [comment]
i'll check it

**Comment by najeebkp** [comment]
@lyqht Check it out !

**Comment by lyqht** [comment]
Good job! Thanks for your work on this ✨

**Pull request merged**
